/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.2/samples
 */

plugins {
  java
}

repositories {
  mavenCentral()
}

java {
  sourceCompatibility = JavaVersion.VERSION_17
  targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
  implementation("com.google.code.gson:gson:2.8.8")
  testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")
}

tasks {
  test {
    useJUnitPlatform()
  }
}